# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a MAF file
#'
#' @param file The name of the file to read
#' @return a GenomicBreaks object
#' @export
readMAF <- function(A = 10L) {
    .Call('_GenomicBreaks_readMAF', PACKAGE = 'GenomicBreaks', A)
}

